### ISSUE TITLE
v0.20.1 release missing [BUG]

### ISSUE THREAD

**Issue by adamonsoon** [nikoksr/proji#198]
**To Reproduce**
Try and install Proji with `scoop`, an error will be thrown because the v0.20.1 executable cannot be found.
It looks like the release never made it to GitHub

**Comment by nikoksr** [comment]
@adamonsoon thanks for your report! It should be fixed by now.

A version 0.20.1 of proji was *released unintentionally* and was officially withdrawn. Our CI tool chain has thus automatically updated the configs for `brew` and `scoop`. *I set the configs back to proji version 0.20.0* and they should now work again. Could you maybe test and confirm this for scoop? I don't have a Windows machine at hand right now.

**Comment by nikoksr** [comment]
Checked it myself and its working again. Sorry for the inconvenience.
